### PR TITLE
Aarch test

### PR DESCRIPTION
**Pull request by ocefpaf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by efiring — APPROVED** [review]
Looks plausible upon a quick scan, but that's all I can do.

**Comment by ocefpaf** [comment]
> Looks plausible upon a quick scan, but that's all I can do.

I still need to run the full test suite here to be sure that aarch package works as expected.

**Comment by ocefpaf** [comment]
I wanted to reproduce https://github.com/TEOS-10/GSW-Python/issues/40 and it looks like we git a similar issue:

```
=================================== FAILURES ===================================
--
989 | _________________________ test_check_function[cfcf72] __________________________
990 |  
991 | cfcf = ({'n2min_alpha': array([[3.18312465e-04, 3.13145844e-04, 9.01115850e-05],
992 | [3.18142757e-04, 3.13790954e-04, 6.43...            nan]]), 'Ipt_second_deriv': array([ 7, 24])}, <check_functions.FunctionCheck object at 0x0000ffff08b76528>)
993 |  
994 | def test_check_function(cfcf):
995 | cv, cf, mfunc = cfcf
996 | mfunc.run(locals())
997 | if mfunc.exception is not None or not mfunc.passed:
998 | print('\n', mfunc.name)
999 | print('  ', mfunc.runline)
1000 | print('  ', mfunc.testline)
1001 | if mfunc.exception is None:
1002 | mfunc.exception = ValueError('Calculated values are different from the expected matlab results.')
1003 | >           raise mfunc.exception
1004 | E           ValueError: Calculated values are different from the expected matlab results.
```

@isuruf I know you are busy and this is not a priority but your expertise here is much appreciated. I have no idea how to fix this for aarch.

**Comment by isuruf** [comment]
Does it fail with ppc64le too?

**Comment by ocefpaf** [comment]
> Does it fail with ppc64le too?

Let me add it here. We never tested.

**Comment by ocefpaf** [comment]
@isuruf, your suspicion was correct! It also fails on `ppc64le`.

**Pull request closed without merging**
